import {v4 as uuidv4} from 'uuid'

export const companies = [
    {id: uuidv4(), "name": "СветТехнологии", "address": "ул. Ленина, 10, Москва", isSelected: false},
    {id: uuidv4(), "name": "ЭкоСтрой", "address": "пр. Мира, 25, Санкт-Петербург", isSelected: false},
    {id: uuidv4(), "name": "Финансовый Центр", "address": "ул. Победы, 5, Екатеринбург", isSelected: false},
    {id: uuidv4(), "name": "ТехноСфера", "address": "ул. Солнечная, 12, Казань", isSelected: false},
    {id: uuidv4(), "name": "АвтоМир", "address": "ул. Садовая, 7, Новосибирск", isSelected: false},
    {id: uuidv4(), "name": "МаркетПлюс", "address": "пр. Лермонтова, 3, Нижний Новгород", isSelected: false},
    {id: uuidv4(), "name": "Строительные Решения", "address": "ул. Пушкина, 20, Самара", isSelected: false},
    {id: uuidv4(), "name": "ITГрупп", "address": "ул. Кирова, 15, Ростов-на-Дону", isSelected: false},
    {id: uuidv4(), "name": "Здоровье и Красота", "address": "пр. Гагарина, 9, Уфа", isSelected: false},
    {id: uuidv4(), "name": "Мода 21", "address": "ул. Октябрьская, 4, Челябинск", isSelected: false},
    {id: uuidv4(), "name": "Креативные Идеи", "address": "ул. Советская, 11, Воронеж", isSelected: false},
    {id: uuidv4(), "name": "ЭкоПродукты", "address": "ул. Мира, 18, Волгоград", isSelected: false},
    {id: uuidv4(), "name": "Гастрономия", "address": "ул. Солнечная, 2, Ярославль", isSelected: false},
    {id: uuidv4(), "name": "Светлая Мысль", "address": "ул. Дружбы, 14, Саратов", isSelected: false},
    {id: uuidv4(), "name": "ПромИнновации", "address": "пр. Победы, 30, Тольятти", isSelected: false},
    {id: uuidv4(), "name": "Детский Мир", "address": "ул. 50 лет Октября, 19, Набережные Челны", isSelected: false},
    {id: uuidv4(), "name": "Энергия Будущего", "address": "ул. Технологическая, 23, Хабаровск", isSelected: false},
    {id: uuidv4(), "name": "Туристическая Компания", "address": "пр. Ленина, 8, Владивосток", isSelected: false},
    {id: uuidv4(), "name": "СтройГрупп", "address": "ул. Кирова, 17, Чита", isSelected: false},
    {id: uuidv4(), "name": "Творческий Центр", "address": "ул. Пушкина, 25, Тула", isSelected: false},
    {id: uuidv4(), "name": "Спорт и Здоровье", "address": "пр. Мира, 5, Сочи", isSelected: false},
    {id: uuidv4(), "name": "Ремонт и Обслуживание", "address": "ул. Октябрьская, 12, Рязань", isSelected: false},
    {id: uuidv4(), "name": "Биофарм", "address": "ул. Садовая, 10, Иваново", isSelected: false},
    {id: uuidv4(), "name": "АгроПром", "address": "ул. Колхозная, 4, Барнаул", isSelected: false},
    {id: uuidv4(), "name": "Косметология", "address": "ул. Красная, 16, Пермь", isSelected: false},
    {id: uuidv4(), "name": "Новые Технологии", "address": "пр. Комсомольский, 22, Кемерово", isSelected: false},
    {id: uuidv4(), "name": "Генерация Идей", "address": "ул. Прогресса, 7, Мурманск", isSelected: false},
    {id: uuidv4(), "name": "Творчество", "address": "пр. Культуры, 11, Ставрополь", isSelected: false},
    {id: uuidv4(), "name": "Инвестиции", "address": "ул. Финансовая, 13, Орск", isSelected: false},
    {id: uuidv4(), "name": "Кулинарная Мастерская", "address": "ул. Вкусная, 8, Сургут", isSelected: false},
    {id: uuidv4(), "name": "Студия Дизайна", "address": "пр. Художников, 9, Ульяновск", isSelected: false},
    {id: uuidv4(), "name": "Гармония", "address": "ул. Чистоты, 6, Липецк", isSelected: false},
    {id: uuidv4(), "name": "Специалисты по IT", "address": "ул. Программная, 15, Вологда", isSelected: false},
    {id: uuidv4(), "name": "АвтоСервис", "address": "пр. Автомобилистов, 4, Саранск", isSelected: false},
    {id: uuidv4(), "name": "КиноМир", "address": "ул. Кинематографа, 1, Нальчик", isSelected: false},
    {id: uuidv4(), "name": "Мебель и Интерьер", "address": "пр. Мебельная, 5, Курск", isSelected: false},
    {id: uuidv4(), "name": "КриптоТех", "address": "ул. Блокчейн, 3, Кострома", isSelected: false},
    {id: uuidv4(), "name": "Студия Анимации", "address": "ул. Мультфильмов, 22, Смоленск", isSelected: false},
    {id: uuidv4(), "name": "Научные Исследования", "address": "ул. Научная, 18, Махачкала", isSelected: false},
    {id: uuidv4(), "name": "Клиника Здоровья", "address": "пр. Лекарственный, 20, Тверь", isSelected: false},
    {id: uuidv4(), "name": "Экологические Решения", "address": "ул. Эко, 30, Архангельск", isSelected: false},
    {id: uuidv4(), "name": "Культура и Искусство", "address": "ул. Артистическая, 12, Кострома", isSelected: false},
    {id: uuidv4(), "name": "Новые Грани", "address": "пр. Грани, 14, Пенза", isSelected: false},
    {id: uuidv4(), "name": "Технологии Будущего", "address": "ул. Инноваций, 25, Йошкар-Ола", isSelected: false},
    {id: uuidv4(), "name": "Творческое Объединение", "address": "пр. Художников, 6, Чебоксары", isSelected: false},
    {id: uuidv4(), "name": "Спортивные Услуги", "address": "ул. Спорта, 8, Златоуст", isSelected: false},
    {id: uuidv4(), "name": "Зеленый Город", "address": "пр. Экология, 9, Сызрань", isSelected: false},
    {id: uuidv4(), "name": "Футбол", "address": "ул. Спортивная, 15, Липецк", isSelected: false},
    {id: uuidv4(), "name": "Мир Путешествий", "address": "ул. Путешествий, 4, Анапа", isSelected: false},
    {id: uuidv4(), "name": "Клиентская Поддержка", "address": "пр. Услуг, 12, Балашиха", isSelected: false},
    {id: uuidv4(), "name": "Агентство Недвижимости", "address": "ул. Недвижимость, 7, Сочи", isSelected: false},
    {id: uuidv4(), "name": "Электроника", "address": "ул. Электронная, 16, Уфа", isSelected: false},
    {id: uuidv4(), "name": "Искусственный Интеллект", "address": "пр. AI, 8, Находка", isSelected: false},
    {id: uuidv4(), "name": "Бизнес Идеи", "address": "ул. Бизнес, 10, Шахты", isSelected: false},
    {id: uuidv4(), "name": "Кулинарный Класс", "address": "пр. Кулинария, 5, Таганрог", isSelected: false},
    {id: uuidv4(), "name": "Фотографическое Искусство", "address": "ул. Фотография, 18, Красноярск", isSelected: false},
    {id: uuidv4(), "name": "Мир Строительства", "address": "пр. Строителей, 22, Саров", isSelected: false},
    {id: uuidv4(), "name": "Завод Технологий", "address": "ул. Заводская, 9, Кострома", isSelected: false},
    {id: uuidv4(), "name": "Кинопрокат", "address": "ул. Кинотеатр, 1, Комсомольск-на-Амуре", isSelected: false},
    {id: uuidv4(), "name": "АвтоСпорт", "address": "пр. Авто, 11, Энгельс", isSelected: false},
    {id: uuidv4(), "name": "Гид по Городам", "address": "ул. Гид, 6, Тольятти", isSelected: false},
    {id: uuidv4(), "name": "Умные Технологии", "address": "ул. Умные, 3, Южно-Сахалинск", isSelected: false},
    {id: uuidv4(), "name": "Дизайн Интерьера", "address": "пр. Дизайнеров, 7, Мытищи", isSelected: false},
    {id: uuidv4(), "name": "Путеводитель", "address": "ул. Путеводная, 2, Раменское", isSelected: false},
    {id: uuidv4(), "name": "Экспертные Услуги", "address": "ул. Экспертная, 14, Подольск", isSelected: false},
    {id: uuidv4(), "name": "Научные Исследования", "address": "пр. Научная, 8, Подольск", isSelected: false},
    {id: uuidv4(), "name": "Гармония Жизни", "address": "ул. Гармонии, 3, Старый Оскол", isSelected: false},
    {id: uuidv4(), "name": "Творческая Лаборатория", "address": "ул. Лабораторная, 20, Набережные Челны", isSelected: false},
    {id: uuidv4(), "name": "Футбольный Клуб", "address": "ул. Футбол, 5, Арзамас", isSelected: false},
    {id: uuidv4(), "name": "СветТехнологии", "address": "ул. Ленина, 10, Москва", isSelected: false},
    {id: uuidv4(), "name": "ЭкоСтрой", "address": "пр. Мира, 25, Санкт-Петербург", isSelected: false},
    {id: uuidv4(), "name": "Финансовый Центр", "address": "ул. Победы, 5, Екатеринбург", isSelected: false},
    {id: uuidv4(), "name": "ТехноСфера", "address": "ул. Солнечная, 12, Казань", isSelected: false},
    {id: uuidv4(), "name": "АвтоМир", "address": "ул. Садовая, 7, Новосибирск", isSelected: false},
    {id: uuidv4(), "name": "МаркетПлюс", "address": "пр. Лермонтова, 3, Нижний Новгород", isSelected: false},
    {id: uuidv4(), "name": "Строительные Решения", "address": "ул. Пушкина, 20, Самара", isSelected: false},
    {id: uuidv4(), "name": "ITГрупп", "address": "ул. Кирова, 15, Ростов-на-Дону", isSelected: false},
    {id: uuidv4(), "name": "Здоровье и Красота", "address": "пр. Гагарина, 9, Уфа", isSelected: false},
    {id: uuidv4(), "name": "Мода 21", "address": "ул. Октябрьская, 4, Челябинск", isSelected: false},
    {id: uuidv4(), "name": "Креативные Идеи", "address": "ул. Советская, 11, Воронеж", isSelected: false},
    {id: uuidv4(), "name": "ЭкоПродукты", "address": "ул. Мира, 18, Волгоград", isSelected: false},
    {id: uuidv4(), "name": "Гастрономия", "address": "ул. Солнечная, 2, Ярославль", isSelected: false},
    {id: uuidv4(), "name": "Светлая Мысль", "address": "ул. Дружбы, 14, Саратов", isSelected: false},
    {id: uuidv4(), "name": "ПромИнновации", "address": "пр. Победы, 30, Тольятти", isSelected: false},
    {id: uuidv4(), "name": "Детский Мир", "address": "ул. 50 лет Октября, 19, Набережные Челны", isSelected: false},
    {id: uuidv4(), "name": "Энергия Будущего", "address": "ул. Технологическая, 23, Хабаровск", isSelected: false},
    {id: uuidv4(), "name": "Туристическая Компания", "address": "пр. Ленина, 8, Владивосток", isSelected: false},
    {id: uuidv4(), "name": "СтройГрупп", "address": "ул. Кирова, 17, Чита", isSelected: false},
    {id: uuidv4(), "name": "Творческий Центр", "address": "ул. Пушкина, 25, Тула", isSelected: false},
    {id: uuidv4(), "name": "Спорт и Здоровье", "address": "пр. Мира, 5, Сочи", isSelected: false},
    {id: uuidv4(), "name": "Ремонт и Обслуживание", "address": "ул. Октябрьская, 12, Рязань", isSelected: false},
    {id: uuidv4(), "name": "Биофарм", "address": "ул. Садовая, 10, Иваново", isSelected: false},
    {id: uuidv4(), "name": "АгроПром", "address": "ул. Колхозная, 4, Барнаул", isSelected: false},
    {id: uuidv4(), "name": "Косметология", "address": "ул. Красная, 16, Пермь", isSelected: false},
    {id: uuidv4(), "name": "Новые Технологии", "address": "пр. Комсомольский, 22, Кемерово", isSelected: false},
    {id: uuidv4(), "name": "Генерация Идей", "address": "ул. Прогресса, 7, Мурманск", isSelected: false},
    {id: uuidv4(), "name": "Творчество", "address": "пр. Культуры, 11, Ставрополь", isSelected: false},
    {id: uuidv4(), "name": "Инвестиции", "address": "ул. Финансовая, 13, Орск", isSelected: false},
    {id: uuidv4(), "name": "Кулинарная Мастерская", "address": "ул. Вкусная, 8, Сургут", isSelected: false},
    {id: uuidv4(), "name": "Студия Дизайна", "address": "пр. Художников, 9, Ульяновск", isSelected: false},
    {id: uuidv4(), "name": "Гармония", "address": "ул. Чистоты, 6, Липецк", isSelected: false},
    {id: uuidv4(), "name": "Специалисты по IT", "address": "ул. Программная, 15, Вологда", isSelected: false},
    {id: uuidv4(), "name": "АвтоСервис", "address": "пр. Автомобилистов, 4, Саранск", isSelected: false},
    {id: uuidv4(), "name": "КиноМир", "address": "ул. Кинематографа, 1, Нальчик", isSelected: false},
    {id: uuidv4(), "name": "Мебель и Интерьер", "address": "пр. Мебельная, 5, Курск", isSelected: false},
    {id: uuidv4(), "name": "КриптоТех", "address": "ул. Блокчейн, 3, Кострома", isSelected: false},
    {id: uuidv4(), "name": "Студия Анимации", "address": "ул. Мультфильмов, 22, Смоленск", isSelected: false},
    {id: uuidv4(), "name": "Научные Исследования", "address": "ул. Научная, 18, Махачкала", isSelected: false},
    {id: uuidv4(), "name": "Клиника Здоровья", "address": "пр. Лекарственный, 20, Тверь", isSelected: false},
    {id: uuidv4(), "name": "Экологические Решения", "address": "ул. Эко, 30, Архангельск", isSelected: false},
    {id: uuidv4(), "name": "Культура и Искусство", "address": "ул. Артистическая, 12, Кострома", isSelected: false},
    {id: uuidv4(), "name": "Новые Грани", "address": "пр. Грани, 14, Пенза", isSelected: false},
    {id: uuidv4(), "name": "Технологии Будущего", "address": "ул. Инноваций, 25, Йошкар-Ола", isSelected: false},
    {id: uuidv4(), "name": "Творческое Объединение", "address": "пр. Художников, 6, Чебоксары", isSelected: false},
    {id: uuidv4(), "name": "Спортивные Услуги", "address": "ул. Спорта, 8, Златоуст", isSelected: false},
    {id: uuidv4(), "name": "Зеленый Город", "address": "пр. Экология, 9, Сызрань", isSelected: false},
    {id: uuidv4(), "name": "Футбол", "address": "ул. Спортивная, 15, Липецк", isSelected: false},
    {id: uuidv4(), "name": "Мир Путешествий", "address": "ул. Путешествий, 4, Анапа", isSelected: false},
    {id: uuidv4(), "name": "Клиентская Поддержка", "address": "пр. Услуг, 12, Балашиха", isSelected: false},
    {id: uuidv4(), "name": "Агентство Недвижимости", "address": "ул. Недвижимость, 7, Сочи", isSelected: false},
    {id: uuidv4(), "name": "Электроника", "address": "ул. Электронная, 16, Уфа", isSelected: false},
    {id: uuidv4(), "name": "Искусственный Интеллект", "address": "пр. AI, 8, Находка", isSelected: false},
    {id: uuidv4(), "name": "Бизнес Идеи", "address": "ул. Бизнес, 10, Шахты", isSelected: false},
    {id: uuidv4(), "name": "Кулинарный Класс", "address": "пр. Кулинария, 5, Таганрог", isSelected: false},
    {id: uuidv4(), "name": "Фотографическое Искусство", "address": "ул. Фотография, 18, Красноярск", isSelected: false},
    {id: uuidv4(), "name": "Мир Строительства", "address": "пр. Строителей, 22, Саров", isSelected: false},
    {id: uuidv4(), "name": "Завод Технологий", "address": "ул. Заводская, 9, Кострома", isSelected: false},
    {id: uuidv4(), "name": "Кинопрокат", "address": "ул. Кинотеатр, 1, Комсомольск-на-Амуре", isSelected: false},
    {id: uuidv4(), "name": "АвтоСпорт", "address": "пр. Авто, 11, Энгельс", isSelected: false},
    {id: uuidv4(), "name": "Гид по Городам", "address": "ул. Гид, 6, Тольятти", isSelected: false},
    {id: uuidv4(), "name": "Умные Технологии", "address": "ул. Умные, 3, Южно-Сахалинск", isSelected: false},
    {id: uuidv4(), "name": "Дизайн Интерьера", "address": "пр. Дизайнеров, 7, Мытищи", isSelected: false},
    {id: uuidv4(), "name": "Путеводитель", "address": "ул. Путеводная, 2, Раменское", isSelected: false},
    {id: uuidv4(), "name": "Экспертные Услуги", "address": "ул. Экспертная, 14, Подольск", isSelected: false},
    {id: uuidv4(), "name": "Научные Исследования", "address": "пр. Научная, 8, Подольск", isSelected: false},
    {id: uuidv4(), "name": "Гармония Жизни", "address": "ул. Гармонии, 3, Старый Оскол", isSelected: false},
    {id: uuidv4(), "name": "Творческая Лаборатория", "address": "ул. Лабораторная, 20, Набережные Челны", isSelected: false},
    {id: uuidv4(), "name": "Футбольный Клуб", "address": "ул. Футбол, 5, Арзамас", isSelected: false},    {id: uuidv4(), "name": "СветТехнологии", "address": "ул. Ленина, 10, Москва", isSelected: false},
    {id: uuidv4(), "name": "ЭкоСтрой", "address": "пр. Мира, 25, Санкт-Петербург", isSelected: false},
    {id: uuidv4(), "name": "Финансовый Центр", "address": "ул. Победы, 5, Екатеринбург", isSelected: false},
    {id: uuidv4(), "name": "ТехноСфера", "address": "ул. Солнечная, 12, Казань", isSelected: false},
    {id: uuidv4(), "name": "АвтоМир", "address": "ул. Садовая, 7, Новосибирск", isSelected: false},
    {id: uuidv4(), "name": "МаркетПлюс", "address": "пр. Лермонтова, 3, Нижний Новгород", isSelected: false},
    {id: uuidv4(), "name": "Строительные Решения", "address": "ул. Пушкина, 20, Самара", isSelected: false},
    {id: uuidv4(), "name": "ITГрупп", "address": "ул. Кирова, 15, Ростов-на-Дону", isSelected: false},
    {id: uuidv4(), "name": "Здоровье и Красота", "address": "пр. Гагарина, 9, Уфа", isSelected: false},
    {id: uuidv4(), "name": "Мода 21", "address": "ул. Октябрьская, 4, Челябинск", isSelected: false},
    {id: uuidv4(), "name": "Креативные Идеи", "address": "ул. Советская, 11, Воронеж", isSelected: false},
    {id: uuidv4(), "name": "ЭкоПродукты", "address": "ул. Мира, 18, Волгоград", isSelected: false},
    {id: uuidv4(), "name": "Гастрономия", "address": "ул. Солнечная, 2, Ярославль", isSelected: false},
    {id: uuidv4(), "name": "Светлая Мысль", "address": "ул. Дружбы, 14, Саратов", isSelected: false},
    {id: uuidv4(), "name": "ПромИнновации", "address": "пр. Победы, 30, Тольятти", isSelected: false},
    {id: uuidv4(), "name": "Детский Мир", "address": "ул. 50 лет Октября, 19, Набережные Челны", isSelected: false},
    {id: uuidv4(), "name": "Энергия Будущего", "address": "ул. Технологическая, 23, Хабаровск", isSelected: false},
    {id: uuidv4(), "name": "Туристическая Компания", "address": "пр. Ленина, 8, Владивосток", isSelected: false},
    {id: uuidv4(), "name": "СтройГрупп", "address": "ул. Кирова, 17, Чита", isSelected: false},
    {id: uuidv4(), "name": "Творческий Центр", "address": "ул. Пушкина, 25, Тула", isSelected: false},
    {id: uuidv4(), "name": "Спорт и Здоровье", "address": "пр. Мира, 5, Сочи", isSelected: false},
    {id: uuidv4(), "name": "Ремонт и Обслуживание", "address": "ул. Октябрьская, 12, Рязань", isSelected: false},
    {id: uuidv4(), "name": "Биофарм", "address": "ул. Садовая, 10, Иваново", isSelected: false},
    {id: uuidv4(), "name": "АгроПром", "address": "ул. Колхозная, 4, Барнаул", isSelected: false},
    {id: uuidv4(), "name": "Косметология", "address": "ул. Красная, 16, Пермь", isSelected: false},
    {id: uuidv4(), "name": "Новые Технологии", "address": "пр. Комсомольский, 22, Кемерово", isSelected: false},
    {id: uuidv4(), "name": "Генерация Идей", "address": "ул. Прогресса, 7, Мурманск", isSelected: false},
    {id: uuidv4(), "name": "Творчество", "address": "пр. Культуры, 11, Ставрополь", isSelected: false},
    {id: uuidv4(), "name": "Инвестиции", "address": "ул. Финансовая, 13, Орск", isSelected: false},
    {id: uuidv4(), "name": "Кулинарная Мастерская", "address": "ул. Вкусная, 8, Сургут", isSelected: false},
    {id: uuidv4(), "name": "Студия Дизайна", "address": "пр. Художников, 9, Ульяновск", isSelected: false},
    {id: uuidv4(), "name": "Гармония", "address": "ул. Чистоты, 6, Липецк", isSelected: false},
    {id: uuidv4(), "name": "Специалисты по IT", "address": "ул. Программная, 15, Вологда", isSelected: false},
    {id: uuidv4(), "name": "АвтоСервис", "address": "пр. Автомобилистов, 4, Саранск", isSelected: false},
    {id: uuidv4(), "name": "КиноМир", "address": "ул. Кинематографа, 1, Нальчик", isSelected: false},
    {id: uuidv4(), "name": "Мебель и Интерьер", "address": "пр. Мебельная, 5, Курск", isSelected: false},
    {id: uuidv4(), "name": "КриптоТех", "address": "ул. Блокчейн, 3, Кострома", isSelected: false},
    {id: uuidv4(), "name": "Студия Анимации", "address": "ул. Мультфильмов, 22, Смоленск", isSelected: false},
    {id: uuidv4(), "name": "Научные Исследования", "address": "ул. Научная, 18, Махачкала", isSelected: false},
    {id: uuidv4(), "name": "Клиника Здоровья", "address": "пр. Лекарственный, 20, Тверь", isSelected: false},
    {id: uuidv4(), "name": "Экологические Решения", "address": "ул. Эко, 30, Архангельск", isSelected: false},
    {id: uuidv4(), "name": "Культура и Искусство", "address": "ул. Артистическая, 12, Кострома", isSelected: false},
    {id: uuidv4(), "name": "Новые Грани", "address": "пр. Грани, 14, Пенза", isSelected: false},
    {id: uuidv4(), "name": "Технологии Будущего", "address": "ул. Инноваций, 25, Йошкар-Ола", isSelected: false},
    {id: uuidv4(), "name": "Творческое Объединение", "address": "пр. Художников, 6, Чебоксары", isSelected: false},
    {id: uuidv4(), "name": "Спортивные Услуги", "address": "ул. Спорта, 8, Златоуст", isSelected: false},
    {id: uuidv4(), "name": "Зеленый Город", "address": "пр. Экология, 9, Сызрань", isSelected: false},
    {id: uuidv4(), "name": "Футбол", "address": "ул. Спортивная, 15, Липецк", isSelected: false},
    {id: uuidv4(), "name": "Мир Путешествий", "address": "ул. Путешествий, 4, Анапа", isSelected: false},
    {id: uuidv4(), "name": "Клиентская Поддержка", "address": "пр. Услуг, 12, Балашиха", isSelected: false},
    {id: uuidv4(), "name": "Агентство Недвижимости", "address": "ул. Недвижимость, 7, Сочи", isSelected: false},
    {id: uuidv4(), "name": "Электроника", "address": "ул. Электронная, 16, Уфа", isSelected: false},
    {id: uuidv4(), "name": "Искусственный Интеллект", "address": "пр. AI, 8, Находка", isSelected: false},
    {id: uuidv4(), "name": "Бизнес Идеи", "address": "ул. Бизнес, 10, Шахты", isSelected: false},
    {id: uuidv4(), "name": "Кулинарный Класс", "address": "пр. Кулинария, 5, Таганрог", isSelected: false},
    {id: uuidv4(), "name": "Фотографическое Искусство", "address": "ул. Фотография, 18, Красноярск", isSelected: false},
    {id: uuidv4(), "name": "Мир Строительства", "address": "пр. Строителей, 22, Саров", isSelected: false},
    {id: uuidv4(), "name": "Завод Технологий", "address": "ул. Заводская, 9, Кострома", isSelected: false},
    {id: uuidv4(), "name": "Кинопрокат", "address": "ул. Кинотеатр, 1, Комсомольск-на-Амуре", isSelected: false},
    {id: uuidv4(), "name": "АвтоСпорт", "address": "пр. Авто, 11, Энгельс", isSelected: false},
    {id: uuidv4(), "name": "Гид по Городам", "address": "ул. Гид, 6, Тольятти", isSelected: false},
    {id: uuidv4(), "name": "Умные Технологии", "address": "ул. Умные, 3, Южно-Сахалинск", isSelected: false},
    {id: uuidv4(), "name": "Дизайн Интерьера", "address": "пр. Дизайнеров, 7, Мытищи", isSelected: false},
    {id: uuidv4(), "name": "Путеводитель", "address": "ул. Путеводная, 2, Раменское", isSelected: false},
    {id: uuidv4(), "name": "Экспертные Услуги", "address": "ул. Экспертная, 14, Подольск", isSelected: false},
    {id: uuidv4(), "name": "Научные Исследования", "address": "пр. Научная, 8, Подольск", isSelected: false},
    {id: uuidv4(), "name": "Гармония Жизни", "address": "ул. Гармонии, 3, Старый Оскол", isSelected: false},
    {id: uuidv4(), "name": "Творческая Лаборатория", "address": "ул. Лабораторная, 20, Набережные Челны", isSelected: false},
    {id: uuidv4(), "name": "Футбольный Клуб", "address": "ул. Футбол, 5, Арзамас", isSelected: false},    {id: uuidv4(), "name": "СветТехнологии", "address": "ул. Ленина, 10, Москва", isSelected: false},
    {id: uuidv4(), "name": "ЭкоСтрой", "address": "пр. Мира, 25, Санкт-Петербург", isSelected: false},
    {id: uuidv4(), "name": "Финансовый Центр", "address": "ул. Победы, 5, Екатеринбург", isSelected: false},
    {id: uuidv4(), "name": "ТехноСфера", "address": "ул. Солнечная, 12, Казань", isSelected: false},
    {id: uuidv4(), "name": "АвтоМир", "address": "ул. Садовая, 7, Новосибирск", isSelected: false},
    {id: uuidv4(), "name": "МаркетПлюс", "address": "пр. Лермонтова, 3, Нижний Новгород", isSelected: false},
    {id: uuidv4(), "name": "Строительные Решения", "address": "ул. Пушкина, 20, Самара", isSelected: false},
    {id: uuidv4(), "name": "ITГрупп", "address": "ул. Кирова, 15, Ростов-на-Дону", isSelected: false},
    {id: uuidv4(), "name": "Здоровье и Красота", "address": "пр. Гагарина, 9, Уфа", isSelected: false},
    {id: uuidv4(), "name": "Мода 21", "address": "ул. Октябрьская, 4, Челябинск", isSelected: false},
    {id: uuidv4(), "name": "Креативные Идеи", "address": "ул. Советская, 11, Воронеж", isSelected: false},
    {id: uuidv4(), "name": "ЭкоПродукты", "address": "ул. Мира, 18, Волгоград", isSelected: false},
    {id: uuidv4(), "name": "Гастрономия", "address": "ул. Солнечная, 2, Ярославль", isSelected: false},
    {id: uuidv4(), "name": "Светлая Мысль", "address": "ул. Дружбы, 14, Саратов", isSelected: false},
    {id: uuidv4(), "name": "ПромИнновации", "address": "пр. Победы, 30, Тольятти", isSelected: false},
    {id: uuidv4(), "name": "Детский Мир", "address": "ул. 50 лет Октября, 19, Набережные Челны", isSelected: false},
    {id: uuidv4(), "name": "Энергия Будущего", "address": "ул. Технологическая, 23, Хабаровск", isSelected: false},
    {id: uuidv4(), "name": "Туристическая Компания", "address": "пр. Ленина, 8, Владивосток", isSelected: false},
    {id: uuidv4(), "name": "СтройГрупп", "address": "ул. Кирова, 17, Чита", isSelected: false},
    {id: uuidv4(), "name": "Творческий Центр", "address": "ул. Пушкина, 25, Тула", isSelected: false},
    {id: uuidv4(), "name": "Спорт и Здоровье", "address": "пр. Мира, 5, Сочи", isSelected: false},
    {id: uuidv4(), "name": "Ремонт и Обслуживание", "address": "ул. Октябрьская, 12, Рязань", isSelected: false},
    {id: uuidv4(), "name": "Биофарм", "address": "ул. Садовая, 10, Иваново", isSelected: false},
    {id: uuidv4(), "name": "АгроПром", "address": "ул. Колхозная, 4, Барнаул", isSelected: false},
    {id: uuidv4(), "name": "Косметология", "address": "ул. Красная, 16, Пермь", isSelected: false},
    {id: uuidv4(), "name": "Новые Технологии", "address": "пр. Комсомольский, 22, Кемерово", isSelected: false},
    {id: uuidv4(), "name": "Генерация Идей", "address": "ул. Прогресса, 7, Мурманск", isSelected: false},
    {id: uuidv4(), "name": "Творчество", "address": "пр. Культуры, 11, Ставрополь", isSelected: false},
    {id: uuidv4(), "name": "Инвестиции", "address": "ул. Финансовая, 13, Орск", isSelected: false},
    {id: uuidv4(), "name": "Кулинарная Мастерская", "address": "ул. Вкусная, 8, Сургут", isSelected: false},
    {id: uuidv4(), "name": "Студия Дизайна", "address": "пр. Художников, 9, Ульяновск", isSelected: false},
    {id: uuidv4(), "name": "Гармония", "address": "ул. Чистоты, 6, Липецк", isSelected: false},
    {id: uuidv4(), "name": "Специалисты по IT", "address": "ул. Программная, 15, Вологда", isSelected: false},
    {id: uuidv4(), "name": "АвтоСервис", "address": "пр. Автомобилистов, 4, Саранск", isSelected: false},
    {id: uuidv4(), "name": "КиноМир", "address": "ул. Кинематографа, 1, Нальчик", isSelected: false},
    {id: uuidv4(), "name": "Мебель и Интерьер", "address": "пр. Мебельная, 5, Курск", isSelected: false},
    {id: uuidv4(), "name": "КриптоТех", "address": "ул. Блокчейн, 3, Кострома", isSelected: false},
    {id: uuidv4(), "name": "Студия Анимации", "address": "ул. Мультфильмов, 22, Смоленск", isSelected: false},
    {id: uuidv4(), "name": "Научные Исследования", "address": "ул. Научная, 18, Махачкала", isSelected: false},
    {id: uuidv4(), "name": "Клиника Здоровья", "address": "пр. Лекарственный, 20, Тверь", isSelected: false},
    {id: uuidv4(), "name": "Экологические Решения", "address": "ул. Эко, 30, Архангельск", isSelected: false},
    {id: uuidv4(), "name": "Культура и Искусство", "address": "ул. Артистическая, 12, Кострома", isSelected: false},
    {id: uuidv4(), "name": "Новые Грани", "address": "пр. Грани, 14, Пенза", isSelected: false},
    {id: uuidv4(), "name": "Технологии Будущего", "address": "ул. Инноваций, 25, Йошкар-Ола", isSelected: false},
    {id: uuidv4(), "name": "Творческое Объединение", "address": "пр. Художников, 6, Чебоксары", isSelected: false},
    {id: uuidv4(), "name": "Спортивные Услуги", "address": "ул. Спорта, 8, Златоуст", isSelected: false},
    {id: uuidv4(), "name": "Зеленый Город", "address": "пр. Экология, 9, Сызрань", isSelected: false},
    {id: uuidv4(), "name": "Футбол", "address": "ул. Спортивная, 15, Липецк", isSelected: false},
    {id: uuidv4(), "name": "Мир Путешествий", "address": "ул. Путешествий, 4, Анапа", isSelected: false},
    {id: uuidv4(), "name": "Клиентская Поддержка", "address": "пр. Услуг, 12, Балашиха", isSelected: false},
    {id: uuidv4(), "name": "Агентство Недвижимости", "address": "ул. Недвижимость, 7, Сочи", isSelected: false},
    {id: uuidv4(), "name": "Электроника", "address": "ул. Электронная, 16, Уфа", isSelected: false},
    {id: uuidv4(), "name": "Искусственный Интеллект", "address": "пр. AI, 8, Находка", isSelected: false},
    {id: uuidv4(), "name": "Бизнес Идеи", "address": "ул. Бизнес, 10, Шахты", isSelected: false},
    {id: uuidv4(), "name": "Кулинарный Класс", "address": "пр. Кулинария, 5, Таганрог", isSelected: false},
    {id: uuidv4(), "name": "Фотографическое Искусство", "address": "ул. Фотография, 18, Красноярск", isSelected: false},
    {id: uuidv4(), "name": "Мир Строительства", "address": "пр. Строителей, 22, Саров", isSelected: false},
    {id: uuidv4(), "name": "Завод Технологий", "address": "ул. Заводская, 9, Кострома", isSelected: false},
    {id: uuidv4(), "name": "Кинопрокат", "address": "ул. Кинотеатр, 1, Комсомольск-на-Амуре", isSelected: false},
    {id: uuidv4(), "name": "АвтоСпорт", "address": "пр. Авто, 11, Энгельс", isSelected: false},
    {id: uuidv4(), "name": "Гид по Городам", "address": "ул. Гид, 6, Тольятти", isSelected: false},
    {id: uuidv4(), "name": "Умные Технологии", "address": "ул. Умные, 3, Южно-Сахалинск", isSelected: false},
    {id: uuidv4(), "name": "Дизайн Интерьера", "address": "пр. Дизайнеров, 7, Мытищи", isSelected: false},
    {id: uuidv4(), "name": "Путеводитель", "address": "ул. Путеводная, 2, Раменское", isSelected: false},
    {id: uuidv4(), "name": "Экспертные Услуги", "address": "ул. Экспертная, 14, Подольск", isSelected: false},
    {id: uuidv4(), "name": "Научные Исследования", "address": "пр. Научная, 8, Подольск", isSelected: false},
    {id: uuidv4(), "name": "Гармония Жизни", "address": "ул. Гармонии, 3, Старый Оскол", isSelected: false},
    {id: uuidv4(), "name": "Творческая Лаборатория", "address": "ул. Лабораторная, 20, Набережные Челны", isSelected: false},
    {id: uuidv4(), "name": "Футбольный Клуб", "address": "ул. Футбол, 5, Арзамас", isSelected: false},
]